package ncollins.salt.words;

public class Nouns {
    public static String[] values = {
        "Amateur",
        "Animal",
        "Ape",
        "Apefucker",
        "Arse",
        "Arse-licker",
        "Arsebreath",
        "Arsecunt",
        "Arseface",
        "Arsehole",
        "Ass",
        "Ass kisser",
        "Ass nugget",
        "Ass clown",
        "Asscunt",
        "Assface",
        "Asshat",
        "Asshole",
        "Assmonkey",
        "Asswagon",
        "Assweed",
        "Asswipe",
        "Aunt fucker",
        "Baby",
        "Badass",
        "Badgerfucker",
        "Bag of dicks",
        "Bandit",
        "Barbarian",
        "Bastard",
        "Beetlehead",
        "Beginner",
        "Bimbo",
        "Birdbrain",
        "Bitch",
        "Bitchface",
        "Bitchwad",
        "Bitchzilla",
        "Blockhead",
        "Blubber gut",
        "Bogeyman",
        "Bonehead",
        "Booby",
        "Bootlicker",
        "Boozer",
        "Boyfucker",
        "Bozo",
        "Brotherfucker",
        "Buffoon",
        "Bum",
        "Bum-fucker",
        "Bum chum",
        "Burden",
        "Buttfucker",
        "Butthead",
        "Butthole",
        "Buttlicker",
        "Chauvinist",
        "Cheater",
        "Chicken",
        "Chickenfucker",
        "Childfucker",
        "Chump",
        "Clown",
        "Cock",
        "Cockboy",
        "Cockfucker",
        "Cockhead",
        "Cockholster",
        "Cockmaster",
        "Cockroach",
        "Cocksucker",
        "Cockwomble",
        "Con man",
        "Country bumpkin",
        "Cousinfucker",
        "Cow",
        "Crack whore",
        "Craphole",
        "Creep",
        "Cretin",
        "Cumstain",
        "cum guzzler",
        "cum bucket",
        "Cunt",
        "Cunt fart",
        "Cuntass",
        "Cuntbitch",
        "Cuntlicker",
        "Cuntsucker",
        "Cuntzilla",
        "Daughterfucker",
        "Deadhead",
        "Degenerate",
        "Der-brain",
        "Dick",
        "Dick-licker",
        "Dickbag",
        "Dickface",
        "Dickfucker",
        "dick sucker",
        "dick chugger",
        "dick lover",
        "dick tickler",
        "Dickhead",
        "Dicktard",
        "Dimwit",
        "Dirtbag",
        "Dirthead",
        "Dodo",
        "Dogfucker",
        "Donkey",
        "Donkeyfucker",
        "Doofus",
        "Dope",
        "Douche",
        "Douche bag",
        "Douchelord",
        "Drunkard",
        "Duckfucker",
        "Dumbass",
        "Dumbbell",
        "Dumbo",
        "Dummy",
        "Egotist",
        "Fagtard",
        "fart sniffer",
        "farty pants",
        "Fart",
        "Fatso",
        "Fibber",
        "Fool",
        "Freak",
        "Fruitcake",
        "Fuck",
        "Fuck noggin",
        "Fuck nugget",
        "Fuckbait",
        "Fuckbucket",
        "Fucker",
        "Fuckhead",
        "Fucklord",
        "Fucktard",
        "Fucktoy",
        "Fuckweasel",
        "Gold digger",
        "Goon",
        "Gorilla",
        "Grouch",
        "Hillbilly",
        "Hippie",
        "Ho",
        "Hoe",
        "Homo",
        "Hooligan",
        "Horse's ass",
        "Horse's necktie",
        "Horsefucker",
        "Idiot",
        "Ignoramus",
        "Imbecile",
        "Inbred",
        "Intercourser",
        "Jackass",
        "Jackwagon",
        "Jerk",
        "Junkie",
        "Lamebrain",
        "Landwhale",
        "Lard face",
        "Liar",
        "Loser",
        "Low-life",
        "Lunatic",
        "Lunkhead",
        "Mackerel",
        "Megabitch",
        "Megadouche",
        "Monkey",
        "Monster",
        "Moron",
        "Motherfucker",
        "Mucky pup",
        "Mutant",
        "Mutt",
        "Neanderthal",
        "Neckbeard",
        "Nerd",
        "Nerf herder",
        "Nimrod",
        "Nincompoop",
        "Ninny",
        "Nitwit",
        "Nobody",
        "Noodle",
        "Numbnuts",
        "Numbskull",
        "Numskull",
        "Oaf",
        "Oddball",
        "Ogre",
        "Oxygen Thief",
        "Pack",
        "Pain in the ass",
        "Peasant",
        "Pencil dick",
        "Pervert",
        "Pig",
        "Pigfucker",
        "Piggy-wiggy",
        "Pinhead",
        "Pissface",
        "Porno freak",
        "Prick",
        "Pseudo-intellectual",
        "Puppet",
        "Pussyfucker",
        "Quack",
        "Quat",
        "Queer",
        "Querulant",
        "Rat",
        "Ratcatcher",
        "Redneck",
        "Reject",
        "Retard",
        "Riff-raff",
        "Sadist",
        "Saprophyte",
        "Sausage-masseuse",
        "sausage licker",
        "sausage lover",
        "Scumbag",
        "Scumhead",
        "Scumlord",
        "Scuzzbag",
        "Sewer rat",
        "Sheepfucker",
        "Shit-eater",
        "Shit stain",
        "Shitass",
        "Shitbucket",
        "Shithead",
        "Shitneck",
        "Shitnugget",
        "Shitsack",
        "Shitter",
        "Shitweasel",
        "Simpleton",
        "Skullfucker",
        "Skunk",
        "Skunkfucker",
        "Slag",
        "Slave",
        "Sleeze",
        "Sleeze bag",
        "Slob",
        "Slutfucker",
        "Snail",
        "Snob",
        "Snot",
        "Snotball",
        "Snowflake",
        "Son of a bitch",
        "Son of a motherless goat",
        "Son of a whore",
        "Square",
        "Stinker",
        "Stinkhole",
        "Swine",
        "Sycophant",
        "Thundercunt",
        "Toad",
        "Tree hugger",
        "Troll",
        "Trollface",
        "Turd",
        "Turdball",
        "Twat",
        "Twatwaffle",
        "Twerp",
        "Twit",
        "Unclefucker",
        "Vermin",
        "Wacko",
        "Wallflower",
        "Wank stain",
        "Wanker",
        "Weeze Bag",
        "Weirdo",
        "Whore",
        "Whorefucker",
        "Whoreson",
        "Windfucker",
        "Windsucker",
        "Witch",
        "Womanizer",
        "Wretch",
        "Yahoo",
        "Zitface",
        "girl next door",
        "bimbo",
        "gal",
        "wild woman",
        "gentle soul",
        "kept woman",
        "gentlewoman",
        "queen bee",
        "whore",
        "sister",
        "survivor",
        "huntress",
        "child",
        "winch",
        "queen",
        "woman of means",
        "Miss",
        "angel",
        "girlfriend",
        "young girl",
        "escort",
        "maiden",
        "tramp",
        "dame",
        "married woman",
        "redhead",
        "dream girl",
        "woman of her word",
        "damsel",
        "young lady",
        "beauty queen",
        "drama queen",
        "daughter",
        "heiress",
        "mademoiselle",
        "girl",
        "grandmother",
        "witch",
        "snuggler",
        "nag",
        "lady",
        "mommy",
        "party girl",
        "young woman",
        "chick",
        "cheater",
        "aunt",
        "hypocrite",
        "girly girl",
        "darling",
        "lady friend",
        "working girl",
        "woman about town",
        "heroine",
        "Ms.",
        "woman",
        "belle",
        "she-devil",
        "mistress",
        "mother",
        "hag",
        "brunette",
        "bitch",
        "floozy",
        "diva",
        "princess",
        "wife",
        "loner",
        "teenager",
        "provider",
        "mom",
        "sportswoman",
        "cover girl",
        "Immoral Asshole",
        "Injurious Bitch",
        "Obscene Dick",
        "Horrifying Dickhead",
        "Vile Douche",
        "Nocuous Douchebag",
        "Abominable Fool",
        "Nasty Idiot",
        "Harmful Jerk",
        "Swinish Loser",
        "Detestable Ass",
        "Horrible Boob",
        "Sinful Buffoon",
        "Rotten Clown",
        "Offensive Idiot",
        "Abhorrent Jerk",
        "Execrable Moron",
        "Unworthy Nerd",
        "Shocking Nitwit",
        "Disturbing Stooge",
        "Evil Sucker",
        "Malevolent Twit",
        "Reprehensible Birdbrain",
        "Vicious Blockhead",
        "Lousy Bonehead",
        "Nefarious Bore",
        "Dreadful Cretin",
        "Iniquitous Dimwit",
        "Barbaric Dolt",
        "Reprobate Dope",
        "Disagreeable Dunce",
        "Horrific Dunderhead",
        "Abject Fathead",
        "Scandalous Goose",
        "Heinous Ignoramus",
        "Infamous Illiterate",
        "Worthless Imbecile",
        "Contemptible Innocent",
        "Dismaying Lightweight",
        "Wicked Maroon",
        "Repellent No-Show",
        "Disheartening Refugee",
        "Repugnant Slacker",
        "Awful Traitor",
        "Horrid Betrayer",
        "Cursed Criminal",
        "Displeasing Defector",
        "Egregious Delinquent",
        "Fiendish Lawbreaker",
        "Odious Loon",
        "Ignoble Nincompoop",
        "Infernal Ninny",
        "Horrendous Numskull",
        "Hideous Oaf",
        "Woeful Sap",
        "Diabolical Simpleton",
        "Hellish Twerp",
        "Unpalatable Ox",
        "Galling Prick",
        "Loathsome Pussy",
        "Repulsive Shit",
        "Ghastly Slut",
        "Sordid Dumb Ass",
        "Treacherous Ass",
        "Ruinous Jackass",
        "Atrocious Prick",
        "Deleterious Cocksucker",
        "Villainous Dickhead",
        "Foul Motherfucker",
        "Appalling Shit",
        "Terrible Son Of A Bitch",
        "Noxious Asshat",
        "Nauseating Asswipe",
        "Monstrous Idiot",
        "Grievous Jerk",
        "Icky Pig",
        "Mischievous Idiot",
        "Detrimental Schmuck",
        "Sinister Asshole",
        "Beastly Black Sheep",
        "Distasteful Derelict",
        "Annoying Wino",
        "Disgusting Jerk",
        "inappropriate jerk",
        "run-and-gun bully",
        "dead lettuce",
        "snuggly screw-up",
        "cold-hearted eskimo",
        "ribbed antidepressant drug",
        "evil stir stick",
        "vintage dream-crusher",
        "heartbreaking stick figure",
        "limp striped hyena",
        "four-wheel drive snake-in-the-grass",
        "sneaky nudist",
        "vibrant chauvinist",
        "grumpy grandma",
        "full of rage fraud",
        "shady dog",
        "overweight basket case",
        "frightening smell",
        "distended mistake",
        "watchful floozy",
        "undersized wiley coyote",
        "superior manure",
        "gloomy promise-breaker",
        "mixed breed physical abuse",
        "wear-anywhere moron",
        "ultimate dog poop",
        "jackass",
        "creamy dummy",
        "grouchy remnant of chaos",
        "humiliating big jerk",
        "dingle berry",
        "state-of-the-art catastrophe",
        "wild ass face",
        "nimble indiscriminate killer",
        "terrifying bored child",
        "heartwarming enemy",
        "narrow-minded pancake",
        "supernatural son-of-a-bitch",
        "asymmetrical butt hole",
        "chunky drug addict",
        "affectionate thief",
        "racist fuckin shit",
        "fluffy poser",
        "freshly brewed meanie",
        "supersoft lunatic",
        "imbalanced dick",
        "at-the-ready fluff ball",
        "timeless towelette",
        "contemporary queen",
        "content dirtbag",
        "flat-chested man of filth",
        "spectacular brat",
        "twisted snake-in-the-grass",
        "long-legged whore",
        "easy-to-drive schmuck",
        "common toilet seat",
        "offensive son-of-a-bitch",
        "backstabbing whore",
        "visual shell of a person",
        "playful bully",
        "silky soft loser",
        "bitchy peace offering",
        "strange kitty cat",
        "tiny-dick",
        "confrontational freak",
        "sadistic manipulator",
        "fully lined suckling pig",
        "trustworthy backstabber",
        "elephantine pig",
        "straight phony",
        "crawly mistake",
        "out-of-control nightmare",
        "irrational gold-digger",
        "sawed-off scumbag",
        "double-crossing bitch",
        "considerate louse",
        "pea-brained waste of a person",
        "submissive wiener",
        "bottled sweet tailpipe",
        "mixed-media princess",
        "quick dingle berry",
        "intoxicating nut job",
        "mutt",
        "deceitful lapdog",
        "brewery-fresh sleazeball",
        "developed wanker",
        "thoughtless cheater",
        "terrible man-whore",
        "odor-absorbing remnant of chaos",
        "lightning-fast cheater",
        "fun freeloader",
        "unacceptable fake",
        "yarn-dyed mimicker",
        "unreliable litter pan",
        "odor-resistant slimeball",
        "long-limbed weed wacker",
        "lonely candlestick maker",
        "narrow unit of unholy depth",
        "glamorous corn cake",
        "neverending friendly claim",
        "single-player scumbucket",
        "crate-trained puppy fucker",
        "instinctual dumbass",
        "outraged fool",
        "irresponsible shit",
        "proprietary outside dog",
        "ridiculous toilet",
        "stiff troublemaker",
        "women’s tentacle",
        "lean monkey",
        "pissed sheep dip",
        "forgettable skinny woman",
        "strapless nut job",
        "chilled good-for-nothing",
        "failure",
        "meaningful clan member",
        "self-centered boner",
        "eager-to-please nightmare",
        "defiant space emulator",
        "chauvinistic pig",
        "silly little girl",
        "full-grown baby",
        "elastic pile of decomposition",
        "dynamic electric furnace",
        "grumpy joke of a person",
        "top-of-the-line bonehead",
        "thirst-quenching backstabber",
        "asymmetrical baby",
        "piece of shit",
        "swindling basket case",
        "cask-conditioned freak",
        "crushing dickhead",
        "staked manipulator",
        "real-time fuzz ball",
        "short-haired selfishness",
        "fat liar",
        "disappointment",
        "psycho waste of a person",
        "caught-in-the-act jackass",
        "purebred marshmallow",
        "cocksucker",
        "brokenhearted druggie",
        "unfiltered manure",
        "killer mental case",
        "two-dimensional pizza cutter",
        "disappointing pervert",
        "mischievous hypocrite",
        "top-level disappointment",
        "nauseating kitty",
        "ghoulishly delightful merry bells",
        "skunk-proof wiener",
        "emotional traitor",
        "furry blunder",
        "oversized attention whore",
        "gangly nonbeliever",
        "crummy marshmallow",
        "thickset terrorist",
        "bat-shit crazy amish person",
        "sleazeball",
        "solid mental case",
        "whiny thief",
        "metallic manipulating ass",
        "jealous bored child",
        "Smegma",
        "big black dick",
        "bigger blacker dick",
        "queef",
        "Pecker",
        "Johnson",
        "Prick",
        "Dick",
        "Cock",
        "Rooster",
        "Lil' willy",
        "Wang",
        "One eyed monster",
        "Trouser snake",
        "Shaft",
        "Weiner",
        "Hot dog",
        "Morning Wood",
        "Pickle",
        "seaman",
        "Turtle Head",
        "sweaty Junk",
        "Bulge",
        "pocket monster",
        "pocket rocket",
        "red rocket",
        "Dong",
        "Sausage",
        "Balls",
        "Stones",
        "Family Jewels",
        "Meatballs",
        "Reece's Pieces",
        "Nuts",
        "Gonads",
        "Huevos",
        "Sack"
    };
}
