package ncollins.hug;

public class Phrases {
    public static String[] values = {
            "{} doesn't read books. He stares them down until he gets the information he wants.",
            "Time waits for no man. Unless that man is {}.",
            "If you spell {} in Scrabble, you win. Forever.",
            "In the Beginning there was nothing ... then {} roundhouse kicked nothing and told it to get a job.",
            "When God said, \"Let there be light!\" {} said, \"Say Please.\"",
            "{} has a mug of nails instead of coffee in the morning.",
            "If {} were to travel to an alternate dimension in which there was another {} and they both fought, they would both win.",
            "The dinosaurs looked at {} the wrong way once. You know what happened to them.",
            "{}' tears cure cancer. Too bad he has never cried.",
            "{} once roundhouse kicked someone so hard that his foot broke the speed of light",
            "If you ask {} what time it is, he always says, 'Two seconds till.' After you ask, 'Two seconds to what?' he roundhouse kicks you in the face.",
            "{} appeared in the 'Street Fighter II' video game, but was removed by Beta Testers because every button caused him to do a roundhouse kick. When asked bout this \"glitch,\" {} replied, \"That's no glitch.\"",
            "Since {} was born, roundhouse kick related deaths have increased 13,000 percent.",
            "{} does not own a stove, oven, or microwave , because revenge is a dish best served cold.",
            "{} does not sleep. He waits.",
            "There is no chin behind {}' beard. There is only another fist.",
            "The chief export of {} is pain.",
            "{} recently had the idea to sell his pee as a canned beverage. It’s now called Red Bull.",
            "If paper beats rock, rock beats scissors, and scissors beats paper, what beats all 3 at the same time? {}.",
            "On the 7th day, God rested ... {} took over.",
            "{} can dribble a bowling ball.",
            "{} drinks napalm to fight his heartburn.",
            "{}' roundhouse kick is so powerful, it can be seen from outer space by the naked eye.",
            "If you want a list of {}' enemies, just check the extinct species list.",
            "{} has never blinked in his entire life. Never.",
            "{} once shot an enemy plane down with his finger, by yelling, \"Bang!\"",
            "{} does not use spell check. If he happens to misspell a word, Oxford will change the spelling.",
            "Some kids pee their name in the snow. {} can pee his name into concrete.",
            "{}' calendar goes straight from March 31st to April 2nd, because no one fools {}.",
            "{} counted to infinity... twice.",
            "{} can have both feet on the ground and kick butt at the same time.",
            "{} can do a wheelie on a unicycle.",
            "{} stands faster than anyone can run.",
            "Once a cobra bit {}' leg. After five days of excruciating pain, the cobra died.",
            "{} once won a game of Connect Four in three moves.",
            "Champions are the breakfast of {}.",
            "When the Boogeyman goes to sleep every night he checks his closet for {}.",
            "{} can slam revolving doors.",
            "{} does not hunt because the word hunting implies the possibility of failure. {} goes killing.",
            "The dark is afraid of {}.",
            "{} can kill two stones with one bird.",
            "{} makes onions cry.",
            "Death once had a near-{} experience.",
            "When {} writes, he makes paper bleed.",
            "{} can strangle you with a cordless phone.",
            "{} never retreats; He just attacks in the opposite direction."
    };
}